// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace loginApi.Models;

public partial class registration
{
    [Key]
    public int Id { get; set; }
    [Required(ErrorMessage = "Please enter a username.")]
    [MinLength(3, ErrorMessage = " at least 3 characters long.")]

    public string username { get; set; }

    [Required(ErrorMessage = "Please enter a EmailAddress.")]

    [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
    public string Email { get; set; }
    [Required(ErrorMessage = "Please enter a password.")]
    
   
    public string password { get; set; }
}